name: "Reader's Lifestyle"
favicon: null
layout_spectrum: 0.8939700562041253
typography_spectrum: 0.685179132502526
title: "Reader's Lifestyle"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2767099137417972
  lightness: 0.38279384933412075
  saturation: 0.6523196341004223
  rhythmicContrast: 0.8264225455932319
purpose: []
